# Generated by Django 2.2 on 2019-09-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateTimeField()),
            ],
        ),
    ]
