# Generated by Django 2.2 on 2019-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maineco', '0004_auto_20190907_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events_img'),
        ),
    ]
