# Generated by Django 2.2.5 on 2019-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, default='users_logos/standart.png', null=True, upload_to='users_logos'),
        ),
    ]
