# Generated by Django 2.2.5 on 2019-10-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups_img')),
                ('name', models.CharField(max_length=255)),
                ('small_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater_group', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
