# Generated by Django 2.2.5 on 2019-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='small_description',
            field=models.CharField(max_length=102),
        ),
    ]
